workflows:
  android-build:
    name: Smart Task Build
    environment:
      java: 17

    scripts:
      - name: Grant permission
        script: chmod +x gradlew

      - name: Build APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
